<?php

namespace AppBundle\Repository;

/**
 * TrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTracks()
	{
		$result = $this->createQueryBuilder('q')
	    ->select('1 AS track, q.name, q.length, q.mp3Name AS file')
	    ->where('q.isVisible = 1')
	    ->orderBy('q.position', 'ASC')
    	->getQuery()
    	->getArrayResult();
		array_walk($result, function (&$item1, $key) { $item1['track'] = ($key+1); });
    	return $result;
	}
}
