easy_admin:
    site_name: 'ADAKADAK Admin'
    design:
        # brand_color: '#eaf3de'
        color_scheme: 'light' 
        menu:
            - { label: 'menu.site', route: 'homepage', icon: 'home' }
            - { entity: 'Track', label: 'menu.track', default: true, icon: 'music' }

    list:
        title: 'list.%%entity_label%%'
        max_results: 30
    show:
        title: '%%entity_label%% (#%%entity_id%%)'
    entities:
        Track:
            class: AppBundle\Entity\Track
            label: 'menu.track'
            form:
                fields:
                    - { property: 'position', label: 'field.position' }
                    - { property: 'name',    label: 'field.name' }
                    - { property: 'length',  label: 'field.length' }
                    - { property: 'isVisible',label: 'field.isVisible' }
                    - { property: 'mp3File', label: 'field.mp3File', type: 'file' }
            list:
                fields: 
                    - { property: 'position', label: 'field.position', type: integer, sortable: true }
                    - { property: 'name',   label: 'field.name',   type: string, sortable: true }
                    - { property: 'length', label: 'field.length', type: string, sortable: true }
                    - { property: 'isVisible', label: 'field.isVisible', type: boolean, sortable: true }
                    - { property: 'updatedAt', label: 'field.updatedAt', type: datetime }
                sort: ['position', 'ASC']

